compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - code: YN0013
    level: discard
  - code: YN0019
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.0.cjs
